#!/usr/bin/env python3
"""Run the negative vectors and emit a machine-readable result.

V1, V2 and V4 are computed here. V3 is not recomputed: it is the frozen KL-005
first-gate probe, which is a committed artifact with its own runner. This file
reads that artifact and pins its digest rather than reimplementing the scoring,
because a second implementation of the same numbers would establish nothing
about the first.

Writes results.json next to this file. Deterministic: rerunning must produce a
byte-identical file.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
KL005_PROBE = ROOT / "research/knowledge-ledger/experiments/KL-005/probe/first-gate.json"

sys.path.insert(0, str(HERE))
import vectors  # noqa: E402


def digest(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def v3_from_artifact() -> dict:
    probe = json.loads(KL005_PROBE.read_text(encoding="utf-8"))
    scores = probe["scores"]
    return {
        "id": "V3",
        "name": "a silent system under a one-sided endpoint",
        "source": {
            "path": "research/knowledge-ledger/experiments/KL-005/probe/first-gate.json",
            "sha256": digest(KL005_PROBE),
            "note": "frozen artifact; regenerated by KL-005 run_first_gate.py",
        },
        "scores": {
            name: {
                "oneSided": s["oneSided"],
                "delayCost": s["delayCost"],
                "twoSided": s["twoSided"],
            }
            for name, s in scores.items()
        },
        "oneSidedWinner": probe["oneSidedWinner"],
        "twoSidedWinner": probe["twoSidedWinner"],
        "silentTiesForBestOneSided": (
            scores["silent"]["oneSided"] == min(s["oneSided"] for s in scores.values())
        ),
        "silentBeatenUnderTwoSidedBy": sorted(
            n for n, s in scores.items()
            if s["twoSided"] < scores["silent"]["twoSided"]
        ),
        "silentIsLastUnderTwoSided": (
            scores["silent"]["twoSided"] == max(s["twoSided"] for s in scores.values())
        ),
    }


def main() -> int:
    document = {
        "schema": "verifier-evidence.vectors.v1",
        "draft": "draft-he-agentproto-verifier-evidence-00",
        "note": (
            "Illustrative vectors for the requirements in the draft. Not a "
            "conformance suite and not a claim about any protocol. Each vector "
            "pairs a check that cannot distinguish its populations with one "
            "that can; the pair is the evidence, not either half."
        ),
        "vectors": [fn() for fn in vectors.ALL] + [v3_from_artifact()],
        "sourceDigests": {
            "vectors.py": digest(HERE / "vectors.py"),
        },
    }
    out = HERE / "results.json"
    out.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}")
    for v in document["vectors"]:
        print(f"  {v['id']}: {v['name']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
